#!/bin/bash

if [ ! -z $1 ] ; then
#	mkdir -p buildlogs
	LOGFILE=make.log

	echo "--- DISTRIBUTION ---" > $LOGFILE
	cat /etc/*release >> $LOGFILE

	echo >> $LOGFILE
	echo "----- GIT  REV -----" >> $LOGFILE
	echo "rev: "$(git log | grep "^commit" | wc -l) >> $LOGFILE
	echo "commit: "$(git log -1 --pretty=format:%H) >> $LOGFILE
	echo "url: "$(git config --get remote.origin.url) >> $LOGFILE

	echo >> $LOGFILE
	echo "--- MAKE  CONFIG ---" >> $LOGFILE
	cat config.local >> $LOGFILE

	echo >> $LOGFILE
	echo "--- MAKE TARGETS ---" >> $LOGFILE
	echo $* >> $LOGFILE

	echo >> $LOGFILE
	echo "---- BUILD  LOG ----" >> $LOGFILE
	time make V=1 $* 2>&1 | tee -a $LOGFILE
else
	echo "Usage: makelog some_commands"
fi
